Repository DeltaRCM/pyDeltaRCM, pull requests merged in 2020-06, with the labels that each got.

#36 BUMBANUMBA
  docs/source/reference/shared_tools/index.rst
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/sed_tools.py
  pyDeltaRCM/shared_tools.py
  pyDeltaRCM/water_tools.py
  requirements.txt
  setup.py
  tests/test_deltaRCM_driver.py
  tests/test_sed_tools.py
  tests/test_shared_tools.py
  tests/test_water_tools.py
  tests/test_yaml_parsing.py
Labels: enhancement

#54 Longer tests, logging, warnings
  pyDeltaRCM/default.yml
  pyDeltaRCM/deltaRCM_tools.py
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/model.py
  pyDeltaRCM/water_tools.py
  run_pyDeltaRCM.py
  tests/test_consistent.py
  tests/test_deltaRCM_tools.py
  tests/test_shared_tools.py
Labels: enhancement, testing

#60 Improve "code quality"
  .bandit.yml
  README.rst
  pyDeltaRCM/deltaRCM_tools.py
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/model.py
  pyDeltaRCM/preprocessor.py
  pyDeltaRCM/sed_tools.py
  pyDeltaRCM/shared_tools.py
  pyDeltaRCM/water_tools.py
Labels: style, testing

#61 Fix: random seed set to int if not provided, support reproducible runs
  pyDeltaRCM/init_tools.py
  tests/test_deltaRCM_tools.py
  tests/test_initialization.py
Labels: bug, enhancement

#65 specify integer type to be compatible with 32-bit systems.
  .github/workflows/build.yml
  pyDeltaRCM/init_tools.py
  tests/test_initialization.py
Labels: bug

#68 cleanup ci scripts, badges, and unrelated and unwanted install script
  .bandit.yml
  .travis.yml
  README.rst
  ez_setup.py
Labels: testing

#70 Fix index error
  .github/workflows/build.yml
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/model.py
  pyDeltaRCM/water_tools.py
  tests/test_consistent.py
  tests/test_init_tools.py
  tests/test_shared_tools.py
Labels: bug
