Repository DeltaRCM/pyDeltaRCM, pull requests merged in 2021-05, with the labels that each got.

#193 working implementation for decoupled basin depth from inlet channel depth
  docs/source/info/yamlparameters.rst
  pyDeltaRCM/default.yml
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/model.py
  pyDeltaRCM/preprocessor.py
  tests/test_init_tools.py
  tests/test_preprocessor.py
Labels: enhancement

#196 Refactor seq
  docs/source/examples/variable_bedload.rst
  docs/source/examples/variable_velocity.rst
  docs/source/guides/advanced_configuration_guide.inc
  docs/source/info/hydrodynamics.rst
  docs/source/pyplots/water_tools/compute_free_surface_outputs.py
  docs/source/reference/model/model_hooks.rst
  docs/source/reference/water_tools/index.rst
  pyDeltaRCM/_version.py
  pyDeltaRCM/hook_tools.py
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/iteration_tools.py
  pyDeltaRCM/model.py
  pyDeltaRCM/sed_tools.py
  pyDeltaRCM/water_tools.py
  tests/integration/test_checkpointing.py
  tests/integration/test_timing_triggers.py
  tests/test_iteration_tools.py
  tests/test_model.py
  tests/test_preprocessor.py
  tests/test_sed_tools.py
  tests/test_water_tools.py
  tests/utilities.py
Labels: style

#201 add a test for the raised RuntimeError on OSError exception
  tests/test_init_tools.py
Labels: testing

#202 Refactor initialization
  docs/source/examples/index.rst
  docs/source/examples/updating_boundary_conditions.rst
  docs/source/examples/variable_velocity.rst
  pyDeltaRCM/init_tools.py
  pyDeltaRCM/model.py
  tests/test_init_tools.py
  tests/test_model.py
Labels: enhancement

#207 Bugfix: hooks for parallel jobs, check calls in test
  pyDeltaRCM/preprocessor.py
  tests/test_preprocessor.py
Labels: bug
